In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine

In [2]:
wine = load_wine()

In [3]:
dir(wine)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [4]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [5]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [6]:
df["target"] = wine.target

In [7]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [8]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [9]:
df["wine_name"] = df.target.apply(lambda x: wine.target_names[x])
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target,wine_name
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0,class_0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0,class_0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0,class_0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0,class_0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0,class_0

In [10]:
df.drop(["alcohol","alcalinity_of_ash","magnesium","proline"], axis=1, inplace=True)

In [11]:
df0 = df[df["wine_name"]=="class_0"]

In [12]:
df1 = df[df["wine_name"]=="class_1"]

In [13]:
df2 = df[df["wine_name"]=="class_2"]

In [14]:
df.head()

,malic_acid,ash,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,target,wine_name
0,1.71,2.43,2.80,3.06,0.28,2.29,5.64,1.04,3.92,0,class_0
1,1.78,2.14,2.65,2.76,0.26,1.28,4.38,1.05,3.40,0,class_0
2,2.36,2.67,2.80,3.24,0.30,2.81,5.68,1.03,3.17,0,class_0
3,1.95,2.50,3.85,3.49,0.24,2.18,7.80,0.86,3.45,0,class_0
4,2.59,2.87,2.80,2.69,0.39,1.82,4.32,1.04,2.93,0,class_0

In [15]:
x = df.drop(["target", "wine_name"], axis=1)

In [16]:
y = df.target

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25)

In [33]:
len(x_test)

45

In [34]:
len(x_train)

133

In [35]:
from sklearn.svm import SVC
model = SVC()

In [36]:
model.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [39]:
model.score(x_test, y_test)

0.9555555555555556

In [40]:
model.predict(x_test)

array([2, 0, 1, 2, 1, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 2, 1, 1, 1, 1, 0,
       2, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 2, 0, 0,
       0])

In [41]:
x_test

,malic_acid,ash,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines
140,2.81,2.70,1.54,0.50,0.53,0.75,4.600000,0.770,2.31
2,2.36,2.67,2.80,3.24,0.30,2.81,5.680000,1.030,3.17
38,1.50,2.10,2.40,2.64,0.28,1.37,3.700000,1.180,2.69
166,3.70,2.60,1.70,0.92,0.43,1.46,10.680000,0.850,1.56
123,5.80,2.13,2.62,2.65,0.30,2.01,2.600000,0.730,3.10
88,2.06,2.46,1.95,1.69,0.48,1.35,2.800000,1.000,2.75
70,1.61,2.21,1.10,1.02,0.37,1.46,3.050000,0.906,1.82
146,5.04,2.23,0.98,0.34,0.40,0.68,4.900000,0.580,1.33
37,1.65,2.55,2.45,2.43,0.29,1.44,4.250000,1.120,2.51
106,1.73,2.12,1.65,2.03,0.37,1.63,3.400000,1.000,3.17
163,3.45,2.35,1.39,0.70,0.40,0.94,5.280000,0.680,1.75
128,1.63,2.30,2.22,2.45,0.40,1.90,2.120000,0.890,2.78
155,5.19,2.32,1.74,0.63,0.61,1.55,7.900000,0.600,1.48
59,0.94,1.36,1.98,0.57,0.28,0.42,1.950000,1.050,1.82
171,2.39,2.28,1.39,0.51,0.48,0.64,9.899999,0.570,1.63
18,1.59,2.48,3.30,3.93,0.32,1.86,8.700000,1.230,2.82
175,4.28,2.26,1.59,0.69,0.43,1.35,10.200000,0.590,1.56
72,1.66,2.24,1.88,1.84,0.27,1.03,3.740000,0.980,2.78
77,2.89,2.23,1.72,1.32,0.43,0.95,2.650000,0.960,2.52
91,1.51,2.42,1.45,1.25,0.50,1.63,3.600000,1.050,2.65
71,1.51,2.67,2.95,2.86,0.21,1.87,3.380000,1.360,3.16
31,1.66,2.36,2.86,3.19,0.22,1.95,6.900000,1.090,2.88
136,4.72,2.54,1.38,0.47,0.53,0.80,3.850000,0.750,1.27
12,1.73,2.41,2.60,2.76,0.29,1.81,5.600000,1.150,2.90
109,1.35,2.70,2.74,2.92,0.29,2.49,2.650000,0.960,3.26
95,1.52,2.20,2.50,2.27,0.32,3.28,2.600000,1.160,2.63
68,0.94,2.36,2.53,1.30,0.55,0.42,3.170000,1.020,1.93
76,0.90,1.71,1.95,2.03,0.24,1.46,4.600000,1.190,2.48
73,1.67,2.60,3.30,2.89,0.21,1.96,3.350000,1.310,3.50
132,2.31,2.40,1.15,1.09,0.27,0.83,5.700000,0.660,1.36
152,1.90,2.75,2.20,1.28,0.26,1.56,7.100000,0.610,1.33
116,1.47,1.99,1.98,1.60,0.30,1.53,1.950000,0.950,3.33
69,1.19,1.75,1.85,1.28,0.14,2.50,2.850000,1.280,3.07
78,0.99,1.95,1.90,1.85,0.35,2.76,3.400000,1.060,2.31
139,2.96,2.61,2.32,0.60,0.53,0.81,4.920000,0.890,2.15
160,3.83,2.38,2.30,0.92,0.50,1.04,7.650000,0.560,1.58
82,1.13,2.51,2.00,1.58,0.40,1.40,2.200000,1.310,2.72
74,1.09,2.30,3.38,2.14,0.13,1.65,3.210000,0.990,3.13
14,1.87,2.38,3.30,3.64,0.29,2.96,7.500000,1.200,3.00
103,1.72,1.88,2.50,1.64,0.37,1.42,2.060000,0.940,2.44
130,1.35,2.32,1.51,1.25,0.21,0.94,4.100000,0.760,1.29
176,2.59,2.37,1.65,0.68,0.53,1.46,9.300000,0.600,1.62
50,1.73,2.04,2.72,3.27,0.17,2.91,7.200000,1.120,2.91
11,1.48,2.32,2.20,2.43,0.26,1.57,5.000000,1.170,2.82
15,1.81,2.70,2.85,2.91,0.30,1.46,7.300000,1.280,2.88

In [42]:
y_test

140    2
2      0
38     0
166    2
123    1
88     1
70     1
146    2
37     0
106    1
163    2
128    1
155    2
59     1
171    2
18     0
175    2
72     1
77     1
91     1
71     1
31     0
136    2
12     0
109    1
95     1
68     1
76     1
73     1
132    2
152    2
116    1
69     1
78     1
139    2
160    2
82     1
74     1
14     0
103    1
130    2
176    2
50     0
11     0
15     0
Name: target, dtype: int32